{
  imports = [
    ./ale.nix
    ./dap.nix
    ./dashboard.nix
    ./fugitive.nix
    ./firenvim.nix
    ./gh.nix
    ./gitsigns.nix
    ./indent-blankline.nix
    ./lsp.nix
    ./leap.nix
    ./lualine.nix
    ./mini.nix
    ./nvim-tree.nix
    ./octo.nix
    ./rest.nix
    ./telescope.nix
    ./toggleterm.nix
    ./treesitter.nix
    ./vim-test.nix
    ./config-local.nix
  ];
}
