{
  imports = [
    ./ale.nix
    ./autoclose.nix
    ./config-local.nix
    ./dap.nix
    ./dashboard.nix
    ./fugitive.nix
    #./firenvim.nix
    #./gh.nix
    ./gitsigns.nix
    ./himalaya.nix
    ./indent-blankline.nix
    ./kitty-navigator.nix
    ./lsp.nix
    ./leap.nix
    ./lualine.nix
    ./mini.nix
    ./nvim-tree.nix
    ./noice.nix
    ./nvim-notify.nix
    ./octo.nix
    ./rest.nix
    ./telescope.nix
    ./toggleterm.nix
    ./treesitter.nix
    ./vim-test.nix
    ./config-local.nix
    ./tiny-glimmer.nix
  ];
}
